In [1]:
import torch

In [2]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [3]:
len(x), x.shape

(4, torch.Size([4]))

## Matrix Transpose

In [4]:
A = torch.arange(20).reshape(4,5)
A, A.T

(tensor([[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]),
 tensor([[ 0,  5, 10, 15],
         [ 1,  6, 11, 16],
         [ 2,  7, 12, 17],
         [ 3,  8, 13, 18],
         [ 4,  9, 14, 19]]))

In [5]:
B = torch.arange(9).reshape(3,3)
B == B.T

tensor([[ True, False, False],
        [False,  True, False],
        [False, False,  True]])

In [6]:
A = torch.arange(12, dtype=torch.float32).reshape(3, 4)
# multiply elementwise
A * A

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.]])

## sum() function

In [7]:
# sum of all elements
A.sum().item()

66.0

In [8]:
A = torch.arange(20, dtype=torch.float32).reshape(2,2,5)
A

tensor([[[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.]],

        [[10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]]])

In [9]:
# shape=[axis=1, axis=2]
print(A.sum(axis=0))
# shape=[axis=1]
print(A.sum(axis=[0, 2]))

tensor([[10., 12., 14., 16., 18.],
        [20., 22., 24., 26., 28.]])
tensor([ 70., 120.])


In [10]:
A = torch.arange(12, dtype=torch.float32).reshape(3,4)

In [11]:
sum_A = A.sum(axis=0, keepdims=True)
sum_A

tensor([[12., 15., 18., 21.]])

In [12]:
# with keepdims=True, we can use broadcast machanism of tensor
# keepdims will fill the rest elemnts with 1
print(A.shape)
print(sum_A.shape)
A / sum_A

torch.Size([3, 4])
torch.Size([1, 4])


tensor([[0.0000, 0.0667, 0.1111, 0.1429],
        [0.3333, 0.3333, 0.3333, 0.3333],
        [0.6667, 0.6000, 0.5556, 0.5238]])

In [13]:
# cumsum()--accumulate in certain axis
A, A.sum(axis=0), A.cumsum(axis=0)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([12., 15., 18., 21.]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  6.,  8., 10.],
         [12., 15., 18., 21.]]))

# Dot production

In [22]:
# vector dot production
x = torch.arange(4, dtype=torch.float32)
y = torch.ones(4, dtype=torch.float32)

torch.dot(x, y)

tensor(6.)

In [15]:
# for vector dot production, both are same
torch.sum(x*y)

tensor(6.)

In [32]:
# matrix-vector dot production
# torch.mv(Matrix, vector)
A = torch.arange(12, dtype=torch.float32).reshape((3,4))
x = torch.arange(4, dtype=torch.float32)
A.shape, x.shape, torch.mv(A, x)

(torch.Size([3, 4]), torch.Size([4]), tensor([14., 38., 62.]))

In [33]:
# matrix production
A = torch.arange(12, dtype=torch.float32).reshape((3,4))
B = torch.arange(12, dtype=torch.float32).reshape((4,3))
torch.mm(A, B)

tensor([[ 42.,  48.,  54.],
        [114., 136., 158.],
        [186., 224., 262.]])

## Norm

In [36]:
# L2 norm--for vector
torch.norm(x)

tensor(3.7417)

In [37]:
# LF norm--for matrix(just lik L2 norm)
torch.norm(A)

tensor(22.4944)

In [38]:
# L1 norm--same for vector & matrix
torch.abs(A).sum()

tensor(66.)