# Check information of Nvidia GPU

In [1]:
!nvidia-smi

zsh:1: command not found: nvidia-smi


In [6]:
import torch
from torch import nn

torch.device('cpu'), torch.cuda.device('cuda'), torch.cuda.device('cuda:1')

(device(type='cpu'),
 <torch.cuda.device at 0x17857d7c0>)

# Check GPU devices

In [7]:
# show the number of available GPU
torch.cuda.device_count()

0

In [9]:
def try_gpu(i=0):
    '''return gpu(i), else return cpu'''
    if torch.cuda.device_count() >= i+1:
        return torch.device(f'cuda:{i}')
    return torch.device('cpu')

def try_all_gpus():
    devices = [torch.device(f'cuda:{i}') for i in range(torch.cuda.device_count())]
    return devices if devices else [torch.device('cpu')]

try_gpu(0), try_all_gpus()

(device(type='cpu'), [device(type='cpu')])

# tensor on gpu

In [10]:
x = torch.tensor([1,2,3])
x.device

device(type='cpu')

In [13]:
# try to put tensor on gpu
x = torch.ones(2,3,device=try_gpu(0))
x, x.device

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 device(type='cpu'))

In [15]:
# init tensor in different gpu
x = torch.randn(2,3,device=try_gpu(1))
x, x.device

(tensor([[ 1.0178, -1.3532, -0.4026],
         [-0.4887, -1.5694,  0.7906]]),
 device(type='cpu'))

# For calculation, tensors should be on same device.

In [18]:
# copy x to another gpu device
y=x.cuda(1)

AssertionError: Torch not compiled with CUDA enabled

# Train nn on gpu

In [24]:
net = nn.Sequential(nn.Linear(3,1))

In [27]:
# put net to gpu
net = net.to(device=try_gpu(0))

# note: the data should be on the same gpu
net(x)

tensor([[0.3277],
        [0.8369]], grad_fn=<AddmmBackward>)

# More you should know
Data communication between different devices is quite slow. So pytorch doesn't allow such operation

In [28]:
# cpu->gpu
x = x.cuda(0)

# gpu->cpu
x = x.cpu()

AssertionError: Torch not compiled with CUDA enabled