In [1]:
import torch
from torch import nn
from d2l import torch as d2l

In [2]:
def pool2d(X, pool_size, mode='max'):
    p_h, p_w = pool_size
    Y = torch.zeros((X.shape[0]-p_h+1, X.shape[1]-p_w+1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[0]):
            for j in range(Y.shape[1]):
                if mode=='max':
                    Y[i,j] = X[i:i+p_h,j:j+p_w].max()
                elif mode=='avg':
                    Y[i,j] = X[i:i+p_h,j:j+p_w].mean()
    return Y

In [3]:
X = torch.tensor([[0., 1., 2.],[3.,4.,5.],[6.,7.,8.]])
pool2d(X, (2,2))

tensor([[4., 5.],
        [7., 8.]])

In [5]:
pool2d(X, (2,2), mode='avg')

tensor([[2., 3.],
        [5., 6.]])

# Pytorch version

In [6]:
X = torch.arange(16, dtype=torch.float32).reshape((1,1,4,4))
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

## In pytorch, stride=size of kernel. => No overlap

In [8]:
pool2d = nn.MaxPool2d(3) # 3x3 kernel
pool2d(X)

tensor([[[[10.]]]])

In [9]:
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [11]:
pool2d = nn.MaxPool2d(3, padding=(1,0), stride=(2,3))
pool2d(X)

tensor([[[[ 6.],
          [14.]]]])

In [12]:
X = torch.cat((X, X+1), 1) # add a channel
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])

In [13]:
X.shape

torch.Size([1, 2, 4, 4])